name: frontend_flutter
description: Flutter frontend for AI Interview System
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: "^3.7.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  firebase_analytics: ^12.0.3
  firebase_messaging: ^16.0.3
  file_picker: ^8.0.2
  url_launcher: ^6.2.6
  http: ^1.2.0
  google_sign_in: ^6.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
